version: 0.2

phases:
  pre_build:
    commands:
      - echo Setting up pre-build steps...
      - gradle --version
#      - ./gradlew clean build -x test
      - echo Logging in to Amazon ECR...
      - aws --version
#      - echo accountID- $AWS_ACCOUNT_ID
      - REPOSITORY_URI=211125493623.dkr.ecr.us-east-2.amazonaws.com/aws-accounts-repo
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo "COMMIT_HASH=$COMMIT_HASH"
      - echo "IMAGE_TAG=$IMAGE_TAG"
  build:
    commands:
      - echo Building the application with Gradle...
      - set -e  # Exit on any error
      - ./gradlew build -x test
      - echo Building the Docker image...
#      - IMAGE_TAG=latest
      - IMAGE_REPO_NAME=aws-accounts-repo
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI/$IMAGE_REPO_NAME:$IMAGE_TAG
#      - IMAGE_REPO_NAME=aws-accounts-repo
#      - echo img-repo-name $IMAGE_REPO_NAME
#      - echo img-tag $IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' "account-service" "$REPOSITORY_URI/$IMAGE_REPO_NAME:$IMAGE_TAG" > imagedefinitions.json
      - echo "Generated imagedefinitions.json:"
      - cat imagedefinitions.json
      - echo Build process completed successfully.

artifacts:
  files:
    - imagedefinitions.json
    - build/libs/*.jar # Update the path if needed for your Gradle build output



